#!/usr/bin/env python
#

import replika
import replika.assets
import replika.ingame

import objetos
import personajes

background = replika.assets.image('assets/backbackground.png')
game = replika.new_game(background.size)
scene = game.new_scene(auto_switch=True)
scene.add_asset(background)

corrupto = scene.add_asset(personajes.Corrupto(), position=(0, 300))
scene.add_asset(replika.assets.image('assets/background.png'))
player = scene.add_asset(personajes.Politico(), position=(0, -250))

while game.is_running:
    if replika.key_state(105):
        player.current_action=player.move_left
    if replika.key_state(106):
        player.current_action=player.move_right
    if ((not replika.key_state(105)) and (not replika.key_state(106))):
        player.stop()
    if replika.key_state(1) or (game.frame >= 10000):
        game.quit()
    game.update()
